### ISSUE TITLE
java.lang.SecurityException: unsupported WS-Security profile

### ISSUE THREAD

**Issue by josbeir** [e-Contract/dssp-php#2]
I'm getting the following error when calling uploadDocument 
``java.lang.SecurityException: unsupported WS-Security profile```

Also tried the example code by running it on my local machine, the same error appears.

Used code
```php
$pdfPath = $this->_generatePdf($filesPath . $id.'_unsigned.pdf', $account);

$pdf_handle = fopen($pdfPath, "r");
$pdfData = fread($pdf_handle, 65536);
fclose($pdf_handle);

$session = $dssClient->uploadDocument($pdfData, 'application/pdf');
debug($session);
```

Dev stack:
* OSX 10.10.3
* PHP 5.6.14
* php mcrypt en soap both installed

See screenshot for the stack trace:

![screen shot 2016-03-30 at 15 29 21](https://cloud.githubusercontent.com/assets/26058/14144086/a9dc1e26-f68e-11e5-8c89-d68b84707dc2.png)

**Comment by fcorneli** [comment]
@josbeir We'll investigate this case.

**Comment by fcorneli** [comment]
Fixed via commit https://github.com/e-Contract/dssp-php/commit/724d172943bd77d33642701dbc4ff24705b5a7ac

**Comment by josbeir** [comment]
thanks!
