### ISSUE TITLE
Response error in Safari browser

### ISSUE THREAD

**Issue by vasu290** [e-Contract/dssp-php#3]
![eid issue in safari](https://user-images.githubusercontent.com/44894750/48256023-54fb7c80-e434-11e8-99cb-e62444693c1f.jpg)

We are facing issue when we are getting response (see the screenshot attached) and same thing is working Chrome and Firefox. Could you please look at the issue?

**Comment by fcorneli** [comment]
This is SAML, nothing to do with DSS.
