### ISSUE TITLE
Deprecated: Methods 

### ISSUE THREAD

**Issue by legrandse** [e-Contract/dssp-php#4]
Just a remind that there is a warning using PHP 7.1.30 and higher:
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; DSSSoapClient has a deprecated constructor  on line 626

**Comment by fcorneli** [comment]
Fixed with https://github.com/e-Contract/dssp-php/commit/d219b7e0b0d3a7e9aab4fe61e20da7b912aa09ff
