### ISSUE TITLE
Issue after upgrading PHP from 7.2 to 7.4

### ISSUE THREAD

**Issue by PeterCrea** [e-Contract/dssp-php#5]
In a needed security update, we've upgraded from PHP 7.2.1 to 7.4.30 and now the dssp service is no longer working.
When we redirect to the service we the error: 
```
JBWEB000065: HTTP Status 400 - unknown async:ResponseID
JBWEB000309: type JBWEB000067: Status report
JBWEB000068: message unknown async:ResponseID
JBWEB000069: description JBWEB000120: The request sent by the client was syntactically incorrect.
```
After examining the payload, we've noticed some parameters were missing which come from the session returned by uploadDocument.
We've narrowed it down to the uploadDocument method of the DigitalSignatureServiceClient class which does not seem to work correctly anymore.

**Comment by fcorneli** [comment]
Intern ticket: 11272

**Comment by fcorneli** [comment]
Fixed with https://github.com/e-Contract/dssp-php/commit/d219b7e0b0d3a7e9aab4fe61e20da7b912aa09ff
