### ISSUE TITLE
Issue after upgrading to PHP 8.2

### ISSUE THREAD

**Issue by SanderVanKeer** [e-Contract/dssp-php#6]
After upgrading to PHP 8.2, it appears that the process of signing a document via EID is no longer functioning as expected. It seems that the constructor of the DSSSoapClient is encountering issues. Upon investigation, I've noticed that the uploadDocument function consistently returns the following response:

```
{
  "Result": {
    "ResultMajor": "urn:oasis:names:tc:dss:1.0:resultmajor:RequesterError"
  },
  "Profile": "urn:be:e-contract:dssp:1.0"
}
```

I would like to kindly request your assistance in investigating and resolving this issue. Your help would be greatly appreciated. Thank you!

**Comment by fcorneli** [comment]
Intern ticket: 12559

**Comment by fcorneli** [comment]
Fixed with https://github.com/e-Contract/dssp-php/commit/d219b7e0b0d3a7e9aab4fe61e20da7b912aa09ff
